export { default as Home } from "./Home";
export { default as MaterialsPage } from "./MaterialsPage";
export { default as LoginPage } from "./Loginpage";
export { default as StudentsInSubjectPage } from "./StudentsInSubjectPage";
export { default as contactUs } from "./contactUs";
export { default as StudentMaterialPage } from "./StudentMaterialPage";
export { default as CourseHome } from "./CourseHome";
export { default as StudentProfilePage } from "./StudentProfilePage";
export { default as InstructorProfilePage } from "./InstructorProfilePage";
export { default as NotFoundPage } from "./NotFoundPage";
export { default as MainPageForQuiz } from "../pages/Quiz/MainPageForQuiz";
export { default as QuizCreation } from "../pages/Quiz/QuizCreation";
export { default as ViewQuizDetails } from "../pages/Quiz/ViewQuizDetails";
export { default as MainPageForQuizStudent } from "../pages/Quiz/MainPageForQuizStudent";
export { default as StudentAnswerPage } from "../pages/Quiz/StudentAnswerPage";
export { default as StudentAnswerForAssignmentPage } from "./StudentAnswerForAssignmentPage";
export { default as AssignmentStudentAnswers } from "./AssignmentStudentAnswers";
export { default as AssignmentStudentGrades } from "./AssignmentStudentGrades";
export {default as ViewStudentAnswers} from "./Quiz/ViewStudentAnswers";
export {default as AssignemntFolderNamesForDoctor} from "./Assignment/AssignemntFolderNamesForDoctor";
export {default as StudentGradesAssignment} from "./Assignment/StudentGradesAssignment";
export {default as AssignmentQuizGradesForDoctor} from "./AssignmentQuizGradesForDoctor";
export {default as QuizFolderNamesForDoctor} from "./QuizzesGradesForDoctor/QuizFolderNamesForDoctor";
export {default as StudentGradeQuiz} from "./QuizzesGradesForDoctor/StudentGradeQuiz";
export {default as QuizStudentGrades} from "./QuizStudentGrades";
