export { default as App } from "./App";
export { default as DragImport } from "./DragImport";
export { default as MaterialTableInstructor } from "./MaterialPage/MaterialTableInstructor";
export { default as MaterialTableStudent } from "./MaterialPage/MaterialTableStudent";
export { default as BreadCrumbs } from "./BreadCrumbs";
export { default as TableHeader } from "./MaterialPage/MaterialTableHeader";
export { default as SideBar } from "./WebsiteLayout/Navigator";
export { default as AddMaterialPopOver } from "./MaterialPage/AddMaterialPopOver";
export { default as InstructorProfile } from "./InstructorProfile";
export { default as CreateFileForm } from "./MaterialForms/FileForm";
export { default as CreateFolderForm } from "./MaterialForms/FolderForm";
export { default as RenameForm } from "./MaterialForms/RenameForm";
export { default as MakeQuizForm } from "./QuizMainPageComponentsForms/MakeQuizForm";
export { default as CoursesNavigationButtons } from "./ButtonBases/CoursesNavigationButtons";
export { default as GradesNavigationButtons } from "./ButtonBases/GradesNavigationButtons";
export { default as QuizTableMainInstructor } from "./QuizMainPageComponents/QuizTableMainInstructor";
export { default as QuizTableMainStudent } from "./QuizMainPageComponents/QuizTableMainStudent";
export { default as QuizHeaderMain } from "./QuizMainPageComponents/QuizHeaderMain";
export { default as QuizHeaderCreation } from "./QuizCreationComponents/QuizHeaderCreation";
export { default as QuizStepper } from "./QuizCreationComponents/QuizStepper";
export { default as MCQ } from "./QuizCreationComponents/MCQ";
export { default as TrueFalse } from "./QuizCreationComponents/TrueFalse";
export { default as Match } from "./QuizCreationComponents/Match";
export { default as ViewQuizForInstructor } from "./ViewQuizModelAnswers/ModelAnswerForQuiz";
export { default as ViewMCQ } from "./ViewQuizModelAnswers/ViewMCQ";
export { default as ViewTrueFalse } from "./ViewQuizModelAnswers/ViewTrueFalse";
export { default as ViewMatch } from "./ViewQuizModelAnswers/ViewMatch";
export { default as ViewQuizForStudent } from "./StudentQuizAnswers/ViewQuizForStudent";
export { default as AnswersMCQ } from "./StudentQuizAnswers/AnswersMCQ";
export { default as AnswersTrueFalse } from "./StudentQuizAnswers/AnswersTrueFalse";
export { default as AnswersMatch } from "./StudentQuizAnswers/AnswersMatch";
export { default as GradeDialog } from "./StudentQuizAnswersForm/GradeDialog";
export { default as AssignmentStudentAnswersTable } from "./StudentAssignments/AssignmentStudentAnswersTable";
export { default as UploadExcelSheet } from "./AllassignmentsandquizzesForms/UploadExcelSheet";
export { default as AssignmentStudentAnswersHeader } from "./StudentAssignments/AssignmentStudentAnswersHeader";
export { default as UploadAssignmentAnswers } from "./StudentAssignmentsForm/UploadAssignmentAnswers";
export { default as StudentAssignmentsTable } from "./StudentGrades/StudentAssignmentsTable";
export { default as StudentQuizGrades } from "./StudentGrades/StudentQuizGrades";
export { default as DoctorgetAssignmentsStudentsTable } from "./StudentAssignmentAsnwersForDoctor/DoctorgetAssignmentsStudentsTable";
export { default as DoctorAssignmentsStudensHeader } from "./StudentAssignmentAsnwersForDoctor/DoctorAssignmentsStudensHeader";
export { default as ViewMCQStudentAnswers } from "./studentAnswersViewForGrades/ViewMCQStudentAnswers";
export { default as ViewStudentQuizAnswers } from "./studentAnswersViewForGrades/ViewStudentQuizAnswers";
export { default as ViewTrueFalseStudentAnswers } from "./studentAnswersViewForGrades/ViewTrueFalseStudentAnswers";
export { default as ViewMatchStudentAnswer } from "./studentAnswersViewForGrades/ViewMatchStudentAnswer";
export { default as GradesHeaderMain } from "./StudentGrades/GradesHeaderMain";
export { default as StudentsInSubject } from "./AllStudentsInSubject/StudentsInSubject";
export { default as AllStudentsInSubjectHeaderMain } from "./AllStudentsInSubject/AllStudentsInSubjectHeaderMain";
export { default as AddQuestionTypePopOver } from "./QuizCreationComponents/AddQuestionTypePopOver";
export { default as AssignmentTableMainInstructor } from "./AllAssignemntsGradeForDoctor/AssignmentTableMainInstructor";
export { default as AllStudentsGradesInSpecificAssignment } from "./AllAssignemntsGradeForDoctor/AllStudentsGradesInSpecificAssignment";
export { default as AssignmentGradesHeaderMain } from "./AllAssignemntsGradeForDoctor/AssignmentGradesHeaderMain";
export { default as AllStudentsGradesInSpecificQuiz } from "./AllQuizzesGradesForDoctor/AllStudentsGradesInSpecificQuiz";
export { default as QuizGradesHeaderMain } from "./AllQuizzesGradesForDoctor/QuizGradesHeaderMain";
export { default as QuizTableMainInstructorNames } from "./AllQuizzesGradesForDoctor/QuizTableMainInstructorNames";
export {default as AllGradesInAspecificAssignmentHeader} from "./AllAssignemntsGradeForDoctor/AllGradesInAspecificAssignmentHeader";
export {default as AllGradesInAspecificQuizHeader} from "./AllQuizzesGradesForDoctor/AllGradesInAspecificQuizHeader";
export {default as EditGradesStudentForm } from "./AllassignmentsandquizzesForms/EditGradesStudentForm";
export {default as ExportExcelSheet } from "./AllassignmentsandquizzesForms/ExportExcelSheet";
export {default as StudentGroupsNumberForm} from "./WebsiteLayoutForm/StudentGroupsNumberForm";
export {default as EditStudentGroupForm} from "./AllstudentsInSubjectForms/EditStudentGroupForm";
export {default as EditNumberOfGroupForStudent} from "./AllstudentsInSubjectForms/EditNumberOfGroupForStudent";
export {default as GradesBreadCrumbsHeader} from "./StudentGrades/GradesBreadCrumbsHeader";
export {default as AssignmentGroupNumberForm} from "./MaterialForms/AssignmentGroupNumberForm";
export {default as QuizGroupNumberForm} from "./QuizMainPageComponentsForms/QuizGroupNumberForm";
export {default as EditGradeAppearForm} from "./QuizMainPageComponentsForms/EditGradeAppearForm";
export {default as EditTotalGradeAssignmentForm} from "./MaterialForms/EditTotalGradeAssignmentForm";
export {default as DeleteConfirmDialog} from "./DeleteConfirmDialog";
export {default as UpdateQuiz} from "./QuizMainPageComponentsForms/UpdateQuiz";